const ENGLISH_EXACT_TEXT = new Map([
  ["", ""],
  ["CheckLab", "CheckLab"],
  ["로그인", "Log In"],
  ["아이디", "ID"],
  ["비밀번호", "Password"],
  ["아이디 또는 비밀번호를 확인해 주세요.", "Please check your ID or password."],
  ["실시간 설비 모니터링 플랫폼", "Real-time Asset Monitoring Platform"],
  ["실시간 설비 모니터링", "Real-time Asset Monitoring"],
  ["신세대 모니터링", "Next-generation Monitoring"],
  ["설비의 모든 것을", "Everything About Your Assets"],
  ["한눈에 파악하세요", "See It at a Glance"],
  ["실시간 분석으로 설비 상태를 예측하고, 문제를 사전에 방지하세요.", "Predict asset conditions with real-time analysis and prevent issues before they happen."],
  ["통합 설비 관리", "Integrated Asset Management"],
  ["Site, Location, Asset을 하나의 체계로 연결해 설비 정보를 구조적으로 관리하고, 복잡한 현장 구성도 한눈에 파악할 수 있습니다.", "Connect Site, Location, and Asset into one structure to manage asset information clearly and understand complex field layouts at a glance."],
  ["3D 기반 설비 관찰 및 분석", "3D Asset Observation and Analysis"],
  ["3D 오브젝트를 생성하여 설비를 더욱 직관적으로 확인할 수 있으며, 다양한 각도에서 면밀하게 관찰하고 분석할 수 있습니다.", "Create 3D objects to inspect assets more intuitively and analyze them closely from multiple angles."],
  ["실시간 모니터링과 신속한 대응", "Real-time Monitoring and Fast Response"],
  ["센서 데이터와 경고 알림을 기반으로 설비 상태를 실시간으로 모니터링하고, 이상 상황 발생 시 빠르게 대응하며 이력을 체계적으로 관리할 수 있습니다.", "Monitor asset status in real time using sensor data and warning notifications, respond quickly to abnormal situations, and manage history systematically."],
  ["설비의 상태, 알림, 분석 데이터를 실시간으로 모니터링하세요.", "Monitor asset status, alerts, and analytics in real time."],
  ["테마 전환", "Toggle Theme"],

  ["설정", "Settings"],
  ["계정, 표시, 알림 설정을 관리합니다", "Manage account, display, and notification settings"],
  ["돌아가기", "Back"],
  ["로딩 중...", "Loading..."],
  ["프로필", "Profile"],
  ["사용자 프로필", "User Profile"],
  ["보안", "Security"],
  ["시스템", "System"],
  ["시스템 정보", "System Information"],
  ["관리자", "Admin"],
  ["이메일", "Email"],
  ["연락처", "Contact"],
  ["부서", "Department"],
  ["설비관리팀", "Asset Management Team"],
  ["프로필 수정", "Edit Profile"],
  ["보안 및 계정", "Security and Account"],
  ["비밀번호", "Password"],
  ["변경", "Change"],
  ["현재 비밀번호", "Current Password"],
  ["새 비밀번호", "New Password"],
  ["새 비밀번호 확인", "Confirm New Password"],
  ["비밀번호가 일치하지 않습니다", "Passwords do not match"],
  ["활성 세션", "Active Sessions"],
  ["현재 기기", "Current Device"],
  ["이 세션 로그아웃", "Log Out This Session"],
  ["모든 기기에서 로그아웃", "Log Out of All Devices"],
  ["현재 기기를 포함한 모든 활성 세션이 종료됩니다", "All active sessions, including this device, will be terminated"],
  ["모든 세션 로그아웃", "Log Out All Sessions"],
  ["계정 삭제", "Delete Account"],
  ["이 작업은 되돌릴 수 없습니다. 계정과 모든 관련 데이터가 영구적으로 삭제됩니다.", "This action cannot be undone. Your account and all related data will be permanently deleted."],
  ["표시 설정", "Display Settings"],
  ["알림 설정", "Notification Settings"],
  ["테마 설정", "Theme"],
  ["언어", "Language"],
  ["시간 형식", "Time Format"],
  ["라이트", "Light"],
  ["다크", "Dark"],
  ["밝은 배경과 높은 대비로 표시합니다.", "Use a bright background with high contrast."],
  ["어두운 배경으로 대시보드를 표시합니다.", "Use a dark dashboard background."],
  ["알림 활성화", "Enable Notifications"],
  ["알림 비활성화", "Disable Notifications"],
  ["알림 활성화", "Notifications Enabled"],
  ["알림 비활성화", "Notifications Disabled"],
  ["전역 경고 알림을 표시합니다.", "Show global warning notifications."],
  ["전역 경고 알림을 숨깁니다.", "Hide global warning notifications."],
  ["알림 표시 방법", "Notification Position"],
  ["가운데", "Center"],
  ["상단", "Top"],
  ["우측하단", "Bottom Right"],
  ["우측하단 작게", "Compact Bottom Right"],
  ["화면 중앙에 크게 표시합니다.", "Show a large notification in the center of the screen."],
  ["화면 상단 중앙에 표시합니다.", "Show notifications at the top center of the screen."],
  ["화면 우측 하단에 표시합니다.", "Show notifications at the bottom right of the screen."],
  ["우측 하단에 작은 카드로 표시합니다.", "Show a compact card at the bottom right."],

  ["버전 정보", "Version Information"],
  ["앱 버전", "App Version"],
  ["API 버전", "API Version"],
  ["빌드 날짜", "Build Date"],
  ["마지막 업데이트", "Last Updated"],
  ["환경 정보", "Environment Information"],
  ["환경", "Environment"],
  ["브라우저", "Browser"],
  ["운영 체제", "Operating System"],
  ["노드 정보", "Node Information"],
  ["노드 ID", "Node ID"],
  ["복사", "Copy"],
  ["팁:", "Tip:"],
  ["문제가 발생하면 시스템 정보를 기술 지원팀에 전달해주세요.", "If an issue occurs, share the system information with technical support."],

  ["전체 현황", "Overview"],
  ["현재 위치", "Current Location"],
  ["경보 현황", "Alarm Status"],
  ["설비 관리", "Asset Management"],
  ["공정 관리", "Site Management"],
  ["장소 관리", "Location Management"],
  ["촬영장치 관리", "Camera Management"],
  ["관심영역 관리", "ROI Management"],
  ["관심 영역 관리", "ROI Management"],
  ["임계값 설정", "Threshold Settings"],
  ["임계치 설정", "Threshold Settings"],
  ["판정 규칙 설정", "Judgement Rules"],
  ["사용자 설정", "User Settings"],
  ["공정 선택", "Select Site"],
  ["관제 관리자", "Control Admin"],
  ["공정 관제 대시보드", "Site Control Dashboard"],
  ["공정 관제", "Site Control"],
  ["전체 설비 구조", "All Asset Structure"],
  ["관제 트리", "Monitoring Tree"],
  ["수집 대기", "Waiting for Collection"],
  ["주요 알림", "Key Notifications"],
  ["전달된 주요 알림이 없습니다.", "No key notifications were provided."],
  ["알림 상세 목록 API가 연결되면 이 영역에 실제 알림 행을 표시합니다.", "When the notification detail list API is connected, actual notification rows will appear here."],
  ["상세 보기", "View Details"],
  ["3분간 숨김", "Hide for 3 minutes"],
  ["3분 숨김", "Hide for 3 minutes"],
  ["설비 대시보드", "Asset Dashboard"],
  ["선택된 설비가 없습니다", "No Asset Selected"],
  ["관제 트리에서 공정, 위치, 설비를 선택하세요.", "Select a site, location, and asset from the monitoring tree."],
  ["사이드 메뉴 열기", "Open Side Menu"],
  ["사이드 메뉴 닫기", "Close Side Menu"],
  ["밝은 화면으로 전환", "Switch to Light Mode"],
  ["어두운 화면으로 전환", "Switch to Dark Mode"],
  ["알림", "Notifications"],
  ["사용자 메뉴", "User Menu"],
  ["날짜", "Date"],
  ["현재 시각", "Current Time"],
  ["날짜 확인 중", "Loading date"],
  ["시간 확인 중", "Loading time"],
  ["글로벌 경고 알림", "Global Warning Notifications"],

  ["정상", "Normal"],
  ["요주의", "Caution"],
  ["주의", "Caution"],
  ["경고", "Warning"],
  ["위험", "Danger"],
  ["이상", "Abnormal"],
  ["오류", "Error"],
  ["정보", "Info"],
  ["성공", "Success"],
  ["가동중", "Running"],
  ["비가동", "Stopped"],
  ["미확인", "Unconfirmed"],
  ["확인", "Confirmed"],
  ["미등록", "Not Registered"],
  ["미설정", "Not Set"],
  ["설정 필요", "Setup Required"],
  ["알림 연동", "Alert Linked"],
  ["알림 해제", "Alert Disabled"],
  ["판정 대기", "Waiting for Judgement"],
  ["변화 없음", "No Change"],
  ["현재", "Now"],
  ["닫기", "Close"],
  ["저장", "Save"],
  ["삭제", "Delete"],
  ["수정", "Edit"],
  ["취소", "Cancel"],
  ["등록", "Register"],
  ["건", " items"],
  ["개", "items"],
  ["추가", "Add"],
  ["생성", "Create"],
  ["저장 중", "Saving"],
  ["대기", "Waiting"],
  ["대기 중", "Waiting"],

  ["경보 기록", "Alarm Records"],
  ["설비 KPI", "Asset KPI"],
  ["평균 온도", "Average Temperature"],
  ["최고 온도", "Maximum Temperature"],
  ["최저 온도", "Minimum Temperature"],
  ["입력 전압", "Input Voltage"],
  ["전력 사용량", "Power Usage"],
  ["설비 운전 상태", "Asset Operating Status"],
  ["설비 데이터 판정", "Asset Data Judgement"],
  ["초음파 · 열화상 분석", "Ultrasound and Thermal Analysis"],
  ["수치 데이터 · 임계치 설정", "Metric Data and Threshold Settings"],
  ["초음파 열화상 분석 패널", "Ultrasound Thermal Analysis Panel"],
  ["초음파", "Ultrasound"],
  ["열화상", "Thermal"],
  ["전력", "Power"],
  ["온도", "Temperature"],
  ["피크", "Peak"],
  ["주파수", "Frequency"],
  ["대역", "Band"],
  ["감지", "Detection"],
  ["최고", "Max"],
  ["최저", "Min"],
  ["임계", "Threshold"],
  ["임계치", "Threshold"],
  ["임계 초과", "Over Threshold"],
  ["안정", "Stable"],
  ["임계치와 동일", "Same as Threshold"],
  ["최대 상승 구간", "Largest Rise Segment"],
  ["피크 / 주파수", "Peak / Frequency"],
  ["온도 추이", "Temperature Trend"],
  ["초음파 추이", "Ultrasound Trend"],
  ["통합(초음파, 온도)", "Combined (Ultrasound, Temperature)"],
  ["온도 ℃", "Temperature C"],
  ["초음파 dB", "Ultrasound dB"],
  ["변화 추이 그래프", "Trend Graph"],
  ["추이 그래프 설정", "Trend Graph Settings"],
  ["그래프 설정", "Graph Settings"],
  ["표시 방식", "Display Mode"],
  ["Range 전환 interval", "Range Switch Interval"],
  ["Range 자동 전환", "Auto Switch Range"],
  ["개별", "Separate"],
  ["통합", "Combined"],
  ["초", "sec"],
  ["분", "min"],
  ["시간", "hr"],
  ["일", "days"],
  ["1구간", "1 segment"],
  ["초음파 평균", "Average Ultrasound"],
  ["온도 평균", "Average Temperature"],
  ["온도 최대 상승", "Maximum Temperature Rise"],
  ["평균 최고 지점", "Highest Average Point"],
  ["평균 최저 지점", "Lowest Average Point"],
  ["요주의 기준", "Caution Threshold"],
  ["이상 기준", "Abnormal Threshold"],
  ["설비 임계", "Asset Threshold"],
  ["설비 임계치 설정", "Asset Threshold Settings"],
  ["설비 임계치 설정 닫기", "Close Asset Threshold Settings"],
  ["임계치 저장", "Save Thresholds"],
  ["온도 Warn", "Temperature Warn"],
  ["온도 Critical", "Temperature Critical"],
  ["초음파 Warn", "Ultrasound Warn"],
  ["초음파 Critical", "Ultrasound Critical"],

  ["관심 영역 리스트", "ROI List"],
  ["관심 영역", "ROI"],
  ["카메라 크게 보기에서 관심 영역을 등록하면 이 목록에 표시됩니다.", "ROIs registered in the enlarged camera view will appear here."],
  ["감지 범위 산출 대기", "Waiting for Detection Range"],
  ["3D 영역", "3D Area"],
  ["3D 포인트", "3D Point"],
  ["3D 패널", "3D Panel"],
  ["3D 월드", "3D World"],
  ["3D 월드 · PLY 뷰어", "3D World · PLY Viewer"],
  ["3D 크게 보기", "Open Enlarged 3D View"],
  ["3D 분석 대상 추가", "Add 3D Analysis Target"],
  ["영역 ROI", "Area ROI"],
  ["영역", "Area"],
  ["포인트 지정", "Point Selection"],
  ["포인트", "Point"],
  ["탐색", "Explore"],
  ["사용자 PLY 모델", "User PLY Model"],
  ["PLY 모델", "PLY Model"],
  ["PNG 텍스처", "PNG Texture"],
  ["임시 카메라 이미지", "Temporary Camera Image"],
  ["임시 카메라 영상", "Temporary Camera Video"],
  ["스트림 대기", "Waiting for Stream"],
  ["샘플 모델 생성하기", "Create Sample Model"],
  ["단자부", "Terminal Section"],
  ["케이블 인입부", "Cable Entry"],
  ["좌측 포커스", "Left Focus"],
  ["상단 포커스", "Top Focus"],
  ["카메라", "Camera"],
  ["패널 보기", "Panel View"],
  ["캠 크게 보기", "Open Enlarged Camera View"],
  ["카메라 관심 영역 추가", "Add Camera ROI"],
  ["정밀 분석", "Precision Analysis"],
  ["대상 목록", "Target List"],
  ["분석 대상 없음", "No Analysis Targets"],
  ["대상 설정", "Target Settings"],
  ["선택 영역 설정", "Selected Area Settings"],
  ["새 관심 영역", "New ROI"],
  ["신규 영역", "New Area"],
  ["대상", "Target"],
  ["모드", "Mode"],
  ["방식", "Method"],
  ["지정", "Selection"],
  ["범위", "Range"],
  ["좌표", "Coordinates"],
  ["등록 시각", "Created At"],
  ["측정값", "Measurements"],
  ["민감도", "Sensitivity"],
  ["최고온도", "Max Temperature"],
  ["평균온도", "Average Temperature"],
  ["최저온도", "Min Temperature"],
  ["검출 dB", "Detection dB"],
  ["ROI 미지정", "ROI Not Set"],
  ["카메라 정보 불러오기", "Load Camera Info"],
  ["카메라 등록이 필요합니다", "Camera registration is required"],
  ["불러올 카메라 정보가 없습니다.", "No camera information is available."],
  ["최대 거리", "Max Distance"],
  ["최소 거리", "Min Distance"],

  ["사이트", "Site"],
  ["공정", "Site"],
  ["장소", "Location"],
  ["위치", "Location"],
  ["설비", "Asset"],
  ["설비명", "Asset Name"],
  ["설비 코드", "Asset Code"],
  ["모델명", "Model Name"],
  ["설비 유형", "Asset Type"],
  ["가동 상태", "Operating Status"],
  ["최근 수집", "Last Collected"],
  ["온도 평균 / 최대 / 최소", "Temperature Avg / Max / Min"],
  ["초음파 평균 / 피크", "Ultrasound Avg / Peak"],
  ["주파수 / 검출", "Frequency / Detections"],
  ["종합 판정", "Overall Judgement"],
  ["종합 의견", "Overall Opinion"],
  ["온도 임계", "Temperature Threshold"],
  ["초음파 임계", "Ultrasound Threshold"],
  ["온도 최저/최고", "Temperature Min/Max"],
  ["초음파 피크/주파수", "Ultrasound Peak/Frequency"],
  ["보고서", "Report"],
  ["설비 보고서", "Asset Report"],
  ["인쇄/저장", "Print / Save"],
  ["담당자 이메일 발송", "Send to Manager"],
  ["이메일 전송 중", "Sending Email"],
  ["담당자 이메일을 입력하세요.", "Enter the manager email."],
  ["담당자 이메일을 확인해 주세요.", "Please check the manager email."],
  ["보고서 화면이 아직 준비되지 않았습니다.", "The report screen is not ready yet."],
  ["담당자에게 보고서 이메일 발송을 요청했습니다.", "The report email request has been sent to the manager."],
  ["보고서 이메일 발송에 실패했습니다.", "Failed to send the report email."],
  ["등록된 관심 영역이 없습니다.", "No ROIs have been registered."],
  ["설비명", "Asset Name"],
  ["검출", "Detection"],
  ["검출 개수", "Detection Count"],
  ["검출 없음", "No Detections"],
  ["보고서 생성 중", "Generating Report"],

  ["시스템 이벤트", "System Event"],
  ["임계 알림", "Threshold Alert"],
  ["이벤트 타임라인", "Event Timeline"],
  ["이벤트 메시지가 없습니다.", "No event message."],
  ["알림 메시지가 없습니다.", "No alert message."],
  ["CheckLab 자산", "CheckLab Asset"],
  ["설비 온도 임계 판정", "Asset Temperature Threshold Judgement"],
  ["설비 초음파 임계 판정", "Asset Ultrasound Threshold Judgement"],
  ["온도 이상", "Temperature Abnormal"],
  ["초음파 상승", "Ultrasound Rising"],
  ["전력 변동", "Power Fluctuation"],

  ["이름", "Name"],
  ["설명", "Description"],
  ["담당자", "Manager"],
  ["담당자 이메일", "Manager Email"],
  ["전화번호", "Phone Number"],
  ["주소", "Address"],
  ["메모", "Memo"],
  ["검색", "Search"],
  ["새 공정", "New Site"],
  ["새 장소", "New Location"],
  ["새 설비", "New Asset"],
  ["공정 구성", "Site Structure"],
  ["공정, 장소, 설비 등록", "Register Site, Location, and Asset"],
  ["공정, 위치, 설비 등록", "Register Site, Location, and Asset"],
  ["공정 생성", "Create Site"],
  ["공정 수정", "Edit Site"],
  ["장소 생성", "Create Location"],
  ["장소 수정", "Edit Location"],
  ["설비 생성", "Create Asset"],
  ["설비 수정", "Edit Asset"],
  ["설명 없음", "No description"],
  ["상세", "Details"],
  ["관리", "Manage"],
  ["숨김", "Hide"],
  ["비밀번호가 변경되었습니다", "Password has been changed"],
  ["캐시가 삭제되었습니다", "Cache has been cleared"],
  ["데이터 내보내기가 시작되었습니다", "Data export has started"],
]);

const ENGLISH_PHRASE_REPLACEMENTS = [
  ["설비 보고서", "Asset Report"],
  ["관심 영역", "ROI"],
  ["관심영역", "ROI"],
  ["초음파", "Ultrasound"],
  ["열화상", "Thermal"],
  ["임계치", "Threshold"],
  ["임계값", "Threshold"],
  ["임계", "Threshold"],
  ["판정", "Judgement"],
  ["평균", "Average"],
  ["최대", "Max"],
  ["최소", "Min"],
  ["최고", "Max"],
  ["최저", "Min"],
  ["피크", "Peak"],
  ["주파수", "Frequency"],
  ["온도", "Temperature"],
  ["전력", "Power"],
  ["경보", "Alarm"],
  ["알림", "Notification"],
  ["이벤트", "Event"],
  ["상태", "Status"],
  ["공정", "Site"],
  ["장소", "Location"],
  ["위치", "Location"],
  ["설비", "Asset"],
  ["카메라", "Camera"],
  ["보고서", "Report"],
  ["담당자", "Manager"],
  ["설정", "Settings"],
  ["저장", "Save"],
  ["등록", "Register"],
  ["삭제", "Delete"],
  ["닫기", "Close"],
  ["생성", "Create"],
  ["수정", "Edit"],
  ["이름", "Name"],
  ["대기", "Waiting"],
  ["정상", "Normal"],
  ["요주의", "Caution"],
  ["주의", "Caution"],
  ["경고", "Warning"],
  ["위험", "Danger"],
  ["이상", "Abnormal"],
  ["오류", "Error"],
];

const ENGLISH_REGEX_REPLACEMENTS = [
  [/(\d+(?:\.\d+)?)\s*분간\s*숨김/g, "Hide for $1 minutes"],
  [/x:\s*초/g, "x: sec"],
  [/x:\s*분/g, "x: min"],
  [/x:\s*시간/g, "x: hr"],
  [/x:\s*일/g, "x: days"],
  [/임시\s*관심\s*영역\s*(\d+)/g, "Temporary ROI $1"],
  [/임시\s*카메라\s*이미지/g, "Temporary Camera Image"],
  [/임시\s*카메라\s*영상/g, "Temporary Camera Video"],
  [/카메라\s*(\d+)/g, "Camera $1"],
  [/3D\s*영역\s*(\d+)/g, "3D Area $1"],
  [/3D\s*포인트\s*(\d+)/g, "3D Point $1"],
  [/영역\s*·\s*(.+)/g, "Area · $1"],
  [/포인트\s*·\s*(.+)/g, "Point · $1"],
  [/온도\s*(\d+(?:\.\d+)?)℃\s*·\s*초음파\s*(\d+(?:\.\d+)?)\s*dB/g, "Temperature $1℃ · Ultrasound $2 dB"],
  [/백엔드\s*알림\s*집계\s*(\d+(?:\.\d+)?)\s*건/g, "Backend notification total $1"],
  [/(^|\s)(\d+(?:\.\d+)?)\s*건/g, "$1$2 items"],
  [/(\d+(?:\.\d+)?)\s*건/g, "$1 items"],
  [/(^|\s)(\d+(?:\.\d+)?)\s*개/g, "$1$2"],
  [/(\d+(?:\.\d+)?)\s*초전/g, "$1 sec ago"],
  [/(\d+(?:\.\d+)?)\s*분전/g, "$1 min ago"],
  [/(\d+(?:\.\d+)?)\s*시간전/g, "$1 hr ago"],
  [/(\d+(?:\.\d+)?)\s*일전/g, "$1 days ago"],
  [/(\d+(?:\.\d+)?)\s*초/g, "$1 sec"],
  [/(\d+(?:\.\d+)?)\s*분/g, "$1 min"],
  [/(\d+(?:\.\d+)?)\s*시간/g, "$1 hr"],
  [/(\d+(?:\.\d+)?)\s*일/g, "$1 days"],
  [/(.+)\s*동안/g, "for $1"],
  [/초과\s*(\d+)\s*items/g, "$1 exceeded"],
  [/임계치보다\s*(.+)\s*높음/g, "$1 above threshold"],
  [/임계치보다\s*(.+)\s*낮음/g, "$1 below threshold"],
  [/(\S+)\s*판정 기준 적용/g, "$1 judgement criteria applied"],
  [/3D 범위\s*(.+)/g, "3D range $1"],
  [/3D 좌표\s*(.+)/g, "3D coordinate $1"],
  [/좌표\s*(.+?)\s*·\s*크기\s*(.+)/g, "Coordinate $1 · Size $2"],
  [/(\d+)\s*포인트/g, "$1 points"],
  [/(.+)\s*임계 알림/g, "$1 threshold alert"],
  [/현재 날짜\s*(.+),\s*현재 시간\s*(.+)/g, "Current date $1, current time $2"],
  [/미처리 경보\s*(\d+)\s*items/g, "$1 unresolved alarms"],
];

export function translateText(value, language) {
  if (language !== "en" || typeof value !== "string" || !/[가-힣]/.test(value)) {
    return value;
  }

  return translateKoreanTextToEnglish(value);
}

export function translateStatus(value, language) {
  return translateText(value, language);
}

function translateKoreanTextToEnglish(value) {
  const leadingWhitespace = value.match(/^\s*/)?.[0] ?? "";
  const trailingWhitespace = value.match(/\s*$/)?.[0] ?? "";
  const coreText = value.trim();

  if (!coreText) {
    return value;
  }

  const exactText = ENGLISH_EXACT_TEXT.get(coreText);
  if (exactText !== undefined) {
    return `${leadingWhitespace}${exactText}${trailingWhitespace}`;
  }

  let translatedText = coreText;
  for (const [pattern, replacement] of ENGLISH_REGEX_REPLACEMENTS) {
    translatedText = translatedText.replace(pattern, replacement);
  }

  if (translatedText !== coreText && !/[가-힣]/.test(translatedText)) {
    return `${leadingWhitespace}${translatedText}${trailingWhitespace}`;
  }

  const replacementCandidates = [...ENGLISH_PHRASE_REPLACEMENTS].sort(
    ([firstText], [secondText]) => secondText.length - firstText.length,
  );

  for (const [koreanText, englishText] of replacementCandidates) {
    translatedText = translatedText.replaceAll(koreanText, englishText);
  }

  for (const [pattern, replacement] of ENGLISH_REGEX_REPLACEMENTS) {
    translatedText = translatedText.replace(pattern, replacement);
  }

  return `${leadingWhitespace}${translatedText}${trailingWhitespace}`;
}
